### ISSUE TITLE
Listing connections

### ISSUE THREAD

**Issue by essen** [emqx/quic#207]
Hello! Me again.

In order to write the Cowboy HTTP/3 test suite I need for some cases a way to retrieve the pid of the peer of the connection. For TCP this looks like the `get_remote_pid_tcp` function here: https://git.ninenines.eu/ct_helper.git/tree/src/ct_helper.erl#n124

I need to do something equivalent for QUIC: get the list of connections, go through them until I find the connection with the right peer name, and then get the pid of the controlling process for that connection.

When I have that pid I can then send messages or signals such as `sys:terminate(whatever)` to test graceful connection closure.

Is there perhaps an undocumented way to do this, that I can use, and if not is that something that could be added?

Cheers.

**Comment by qzhuyan** [comment]
Currently not supported. 

But Yes. we need these features:
1. List all the connections.
    
1. get owner pid of handle

I am now adding multi registration support where connections/listeners can be fetched with the registration handle.

note, the peer name of QUIC connection could change due to the address migration feature that the client migrates to a new source address without losing the connection.

**Comment by essen** [comment]
Yes the address can change but for my tests it's all localhost so I don't expect an issue. Thanks!
