### ISSUE TITLE
make: cmake: Permission denied

### ISSUE THREAD

**Issue by mickel8** [emqx/quic#87]
Hi, when I am trying to install `quicer` using `Mix.install` I am getting 

```
[17:38] michal:quicer ((868d5af2…)) | make build-nif
./get-msquic.sh v1.8.0
cmake -B c_build
make: cmake: Permission denied
make: *** [Makefile:22: build-nif] Error 127
```

I also tried to clone and run `make build-nif` manually but I got the same error. When i run `cmake -B c_build` everything works okay :thinking:

**Comment by qzhuyan** [comment]
I could not reproduce the issue. maybe check the cmake version and also try cleanup the dir `msquic`

**Comment by thalesmg** [comment]
I could not reproduce it either.

@mickel8  are you trying to install `0.0.9`? As in `Mix.install([{:quicer, github: "emqx/quic", tag: "0.0.9"}])`?

Mix install puts its stuff under `$HOME/.cache/mix/installs/elixir-$ELIXIR_VSN-erts-$ERTS_VSN/`.  Since the error you are getting suggests permission issues, maybe check that dir and its children for permissions?

**Comment by mickel8** [comment]
Well, adding tag `0.0.9` solved the problem :thinking:

**Comment by mickel8** [comment]
The difference is that `0.0.9` calls `cmake -B build` from `rebar.config` while the `main` calls `cmake -B buil` from `Makefile`

https://github.com/emqx/quic/blob/0.0.9/rebar.config#L5
https://github.com/emqx/quic/blob/main/Makefile#L22

**Comment by mickel8** [comment]
Looks like this was a problem with my OS configuration. Suprisingly, /sbin/cmake doesn't work but /usr/bin/cmake works perfectly despite the fact that /sbin/cmake is a symbolic link to /usr/bin/cmake and it has all permissions
